services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "until python -c 'import socket; s=socket.socket(); s.connect((\"db\",5432)); s.close()'; do echo waiting for db; sleep 1; done; python code/manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data: